---

- name: Generate admin password for OCP
  hosts: local
  gather_facts: false
  tasks:
  - name: Create config file structure
    file:
      path: "{{ directory }}/{{ config_dir }}"
      state: directory
  - name: Set credentials file
    set_fact:
      ocp_credentials_file: "{{ directory }}/{{ config_dir }}/ocp-admin-credentials.json"
  - name: Check if credentials file already exist
    stat:
      path: "{{ ocp_credentials_file }}"
    register: r_ocp_credentials_file
  - name: Read Engagement Data
    include_vars:
      file: "{{ directory }}/engagement.json"
  - name: Only if credentials haven't already been created
    block:
    - name: Create OCP password
      set_fact:
        ocp_password: "{{ lookup('password', '/dev/null length=32 chars=ascii_letters,digits') }}"
    - name: Create OCP credentials file
      copy:
        dest: "{{ ocp_credentials_file }}"
        content: "{{ {'ocp_admin_username':'admin','ocp_admin_password':ocp_password } | to_nice_json }}"
    when:
    - r_ocp_credentials_file.stat.exists == False
    - hosting_environments is defined
    - hosting_environments|length > 0
    - hosting_environments[0].ocp_version is defined
