---
- hosts: all
  tasks:
    - name: 'Fail If Working Directory Is Not Provided'
      fail:
        msg: 'directory var needs to be provided in order to ensure a safe working directory'
      when:
        - directory is undefined or (directory | trim) == ""

    - name: Read Engagement Data
      include_vars:
        file: '{{ directory }}/engagement.json'

    - name: Set customer engagement
      set_fact:
        customer_engagement: "{{ customer_name | lower | replace(' ', '_') }}-{{ project_name | lower | replace(' ', '_') }}"

    - name: Set facts to bootstrap scheduled notifications into Ansible Tower
      set_fact:
        delete_missing_items: false
        ansible_tower:
          url: '{{ ansible_tower_url }}'
          admin_user: '{{ ansible_tower_admin_username }}'
          admin_password: '{{ ansible_tower_admin_password }}'
          credentials:
            - name: '{{ scm_credential_name }}'
              organization: '{{ organization }}'
              credential_type: Source Control
              ssh_key_data: "{{ lookup('file', ssh_key_data_path) }}"
          projects:
            - name: '{{ customer_engagement }}-project'
              description: 'Create project for {{ customer_engagement }}'
              organization: '{{ organization }}'
              scm_type: git
              scm_url: '{{ url }}'
              scm_branch: master
              scm_credential_name: '{{ scm_credential_name }}'
              scm_update_on_launch: true
          inventories:
            - name: '{{ customer_engagement }}-tower_jobs_launch'
              description: 'Inventory for {{ customer_engagement }}'
              organization: '{{ organization }}'
              variables: ''
              hosts:
                - name: localhost
                  variables: |-
                    ---
                    ansible_connection: local
              sources:
                - name: '{{ customer_engagement }}-notifications'
                  description: Source for {{ customer_engagement }}-notifications
                  inventory: '{{ customer_engagement }}-tower_jobs_launch'
                  source: scm
                  source_project: '{{ customer_engagement }}-project'
                  credential: '{{ scm_credential_name }}'
                  source_path: iac/inventories/tower_jobs_schedules/inventory
                  update_on_launch: true
                  source_vars: |-
                    ---
                - name: '{{ customer_engagement }}-tower_jobs_schedules'
                  description: Source for {{ customer_engagement }}-notifications
                  inventory: '{{ customer_engagement }}-tower_jobs_launch'
                  source: scm
                  source_project: '{{ customer_engagement }}-project'
                  credential: '{{ scm_credential_name }}'
                  source_path: iac/inventories/notifications/inventory
                  update_on_launch: true
                  source_vars: |-
                    ---
          job_templates:
            - name: '{{ customer_engagement }}-configure-ansible-tower'
              description: Configure Ansible Tower
              inventory: '{{ customer_engagement }}-tower_jobs_launch'
              project: infra-ansible
              playbook: playbooks/ansible/tower/configure-ansible-tower.yml
              ask_inventory: yes
          launch_jobs:
            - name: Launch Tower Job to configure Scheduled Notifications
              job_template: '{{ customer_engagement }}-configure-ansible-tower'
      when:
        - start_date is defined
        - (hosting_environments is defined) and (hosting_environments | length > 0)
        - engagement_type | default('') == 'Residency'
        - (archive_date | default('2006-01-02T15:04:05.000Z') | to_datetime('%Y-%m-%dT%H:%M:%S.%fZ')).strftime('%s') > now(utc=true).strftime('%s')

- import_playbook: '{{ infra_ansible_directory }}/playbooks/ansible/tower/configure-ansible-tower.yml'
